config/routes.rb
Rails.application.routes.draw do
  resources :messages do
    resources :comments

    get :get_public_messages, :on => :collection
    get :create_new_message, :on => :collection
    get :create_comment, :on => :collection
  end

  root "messages#index"

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessor :user_name
	attr_accessor :user_avatar

	belongs_to :user
	belongs_to :message
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy

	scope :msg_public, lambda { where(:msg_public => true) }
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :full_name

	has_many :messages, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
    @message = Message.find(params[:message_id])
    @comment = @message.comments.create(params[:comment].permit(:content))
    #@comment.user = current_user

    if @comment.save
      redirect_to message_path(@message)
    else
      render('new')
    end
  end

  def edit
    @message = Message.find(params[:message_id])
    @comment = @message.comments.find(params[:id])
  end

  def update
    @message = Message.find(params[:message_id])
    @comment = @message.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:content))
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def delete
  end

  # Params: message_id (Integer), user_id (Integer), content (Text)
  # Example: localhost:3000/comments/create_comment?message_id=&content=&user_id=
  def create_comment
    @user = User.find(params[:user_id])
    @message = Message.find(params[:message_id])
    @comment = @message.comments.create(params.permit(:content))
    @comment.user = @user
    @comment.user_name = @user.id
    @comment.user_avatar = @user.id

    if @comment.save
      response = { "code" => 1, "msg" => "Comment Created Successfully" }
    else
      response = { "code" => 0, "msg" => "Comment Can't be created" }
    end

    render json: response
  end

  def destroy
    @message = Message.find(params[:message_id])
    @comment = @message.comments.find(params[:id])

    @comment.destroy
    redirect_to message_path(@message)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:edit, :update, :delete, :destroy]
  
  def index
    @messages = Message.all
  end

  # Sent Params: id (Integer)
  # Returned Params: Message (id, subject, content, created_at, delivery_date, like_count), User Object (id, full_name, user_avatar), 
  # Comments Object (id, content, user_name, user_avatar)
  # If Failed, the returned params will be code(0), msg
  # Example: http://localhost:3000/messages/show/{message_id}
  def show
    begin
      @message = Message.find params[:id]
      render json: @message, each_serializer: MessageSerializer
    rescue ActiveRecord::RecordNotFound => e
      render json: { "code" => 0, "msg" => "No message found" }
    end
  end

  def new
    @message = Message.new
  end

  # user_id, subject, content, msg_to, delivery_date, delivery_time, msg_public
  def create
    @message = Message.new(message_params)
    @message.msg_public = params[:msg_public]
    @message.user_id = params[:user_id]

    if @message.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @message.update(:msg_public => params[:msg_public])
    if @message.update(message_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def delete
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end

  def like_message
    message = Message.find(params[:id])
    self.increment!(:like_count)

    render :nothing => true
  end

  # Returned Params for each message: id, subject, content, created_at, user_name
  # If Failed, the returned params will be code(0), msg
  # Example: http://localhost:3000/messages/get_public_messages
  def get_public_messages
    @messages = Message.msg_public
    if @messages.empty?
      render json: { "code" => 0, "msg" => "No Messages Found" }
    else
      render json: @messages, each_serializer: PublicMessagesSerializer
    end
  end

  # Sent Params: user_id (Integer), subject (String), content (Text), msg_to (Text), delivery_date (String), delivery_time (String), msg_public (Boolean)
  # Returned Params: code (0 if fails, 1 if succeeded), msg
  # http://localhost:3000/messages/create_new_message?user_id=&subject=&content=&msg_to=&delivery_date=&delivery_time=&msg_public=
  def create_new_message
    @message = Message.new(message_service_params)

    if @message.save
      response = { "code" => 1, "msg" => "Message Created Successfully" }
    else
      response = { "code" => 0, "msg" => "Message Can't be created" }
    end

    render json: response
  end

  private
  def find_message
    @message = Message.find(params[:id])
  end

  def message_service_params
    params.permit(:user_id, :msg_public, :msg_to, :subject, :content, :delivery_date, :delivery_time)
  end

  def message_params
    params.require(:message).permit(:user_id, :msg_public, :msg_to, :subject, :content, :delivery_date, :delivery_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    #render json: @users
  end

  def get_all_users
    @users = User.first
    @users.full_name = @users.first_name + ' ' + @users.last_name
    render json: @users
  end

  def show
    @user = User.find(params[:id])
    #render json: @user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to(:action => 'show', :id => @user.id)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to(:action => 'show', :id => @user.id)
    else
      render 'edit'
    end
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to(:action => 'index')
  end

  # App send email, first_name, last_name, user_avatar
  # Check the email sent from the app
  # If user already exist, respond with the user ID
  # If user doesn't exist, create new user and respond with the user ID
  # If user couldn't be saved, respond with 0
  # Params : email, first_name, last_name, user_avatar
  # Example : http://localhost:3000/users/user_login?email=foo@gmail.com&first_name=foo&last_name=doo&user_avatar=myavatar
  # Response : code, user_id, msg
  def user_login
    @user = User.find_by_email(params[:email])

    if @user.present?
      # response -- User Found and this is his ID
      response = { "code" => 1, "user_id" => @user.id, "msg" => "User Found" }
    else
      new_user = User.new(:email => params[:email], :first_name => params[:first_name], 
        :last_name => params[:last_name], :user_avatar => params[:user_avatar])

      if new_user.save
        # User Not found, will create one and this is his ID
        response = { "code" => 1, "user_id" => new_user.id, "msg" => "New User Created" }
      else
        # response -- with 0, Failed to create new user
        response = { "code" => 0, "msg" => "User Can't be created" }
      end
    end

    # Send the response in JSON
    render json: response
  end

  # Params : user_id
  # Returned Params: id, full_name, user_avatar
  # Example : http://localhost:3000/users/get_user_details?user_id=22
  def get_user_details
    @user = User.find_by_id(params[:user_id])
    render json: @user
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :user_avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %> By: #User</p>
<p><%= link_to "Edit", edit_message_comment_path(@message, comment) %></p>
<p><%= link_to "Delete", message_comment_path(@message, comment), method: :delete, data: { confirm: "Are you sure ?" } %></p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>
<%= form_for [@message, @comment] do |form| %>
	<%= form.text_field :content, :required => true %>
	<%= form.submit %>
<% end %> 

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeCapsule</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
</head>
<body>
	<%= link_to( "Add new message", new_message_path ) %>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>

app/views/messages/delete.html.erb
<h1>Messages#delete</h1>
<p>Find me in app/views/messages/delete.html.erb</p>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= form_for(@message, html: { multipart: true }) do |form| %>
	<%= render :partial => 'shared/msg_form', :locals => {:form => form} %>
<% end %>

app/views/messages/index.html.erb
<h1>All Messages</h1>

<%= link_to( "Add new message", new_message_path ) %>

<table>
	<tr>
		<th>Public</th>
		<th>To</th>
		<th>subject</th>
		<th>content</th>
		<th>Like Count</th>
		<th>Comment Count</th>
		<th>Delivery Date</th>
		<th>Delivery Time</th>
	</tr>

	<% @messages.each do |msg| %>
	<tr>
		<td><%= msg.msg_public %></td>
		<td><%= msg.msg_to %></td>
		<td><%= link_to( msg.subject, message_path(msg) ) %></td>
		<td><%= msg.content %></td>
		<td><%= msg.like_count %></td>
		<td><%= msg.comment_count %></td>
		<td><%= msg.delivery_date %></td>
		<td><%= msg.delivery_time %></td>
	</tr>
	<% end %>
</table>

app/views/messages/new.html.erb
<h1>Add a new message</h1>

<%= form_for(@message, html: { multipart: true }) do |form| %>
	<%= render :partial => "shared/msg_form", :locals => {:form => form} %>
<% end %>

app/views/messages/show.html.erb
<%= link_to( "Edit Message", edit_message_path(@message) ) %>
<%= link_to( "Delete the message", message_path(@message), method: :delete, data: {confirm: 'Are you sure?'} ) %>

<br>
<h2><%= @message.subject %></h2>

<p>Message To: <%= @message.msg_to %></p>
<p>Content: <%= @message.content %></p>
<p>Delivery Date To: <%= @message.delivery_date %></p>
<p>Delivery Time: <%= @message.delivery_time %></p>
<p>Public: <%= @message.msg_public %> </p>

<h4>Likes Count: <%= @message.like_count %> </h4>

<h4>Comments Count: <%= @message.comments.count %> </h4>

<%= render @message.comments %>

<h3>Add a comment</h3>

<%= render 'shared/comment_form' %>

app/views/shared/_comment_form.html.erb
<%= form_for(:comment, :url => {:controller => 'comments', :action => 'create', :message_id => @message.id}) do |form| %>
	<%= form.text_field :content, :required => true %>
	<%= form.submit %>
<% end %> 

app/views/shared/_msg_form.html.erb
Message to: <%= form.text_field :msg_to, :required => true %><br>
Subject: <%= form.text_field :subject, :required => true %><br>
Content: <%= form.text_field :content, :required => true %><br>
Delivery Date: <%= form.text_field :delivery_date, :required => true %><br>
Delivery Time: <%= form.text_field :delivery_time, :required => true %><br>
<%= hidden_field_tag :msg_public, false %>
<%= check_box_tag :msg_public, 'true' %>
<%= label_tag :msg_public, "Make it public" %><br>
<%= form.submit %>

app/views/shared/_user_form.html.erb
<%= form.text_field :email, :required => true %>
	
<%= form.text_field :first_name, :required => true %>

<%= form.text_field :last_name, :required => false %>

<%= form.submit %>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<h2>Edit User</h2>

<%= form_for(:user, :url => {:controller => 'users', :action => 'update', :id => @user.id}, html: { multipart: true }) do |form| %>
	<%= render(:partial => "shared/user_form", :locals => {:form => form}) %>
<% end %>

app/views/users/index.html.erb
<h2>All Users</h2>
<%= link_to( "Add new user", {:controller => 'users', :action => 'new'} ) %>

<table>
	<tr>
		<th>User ID</th>
		<th>User Mail</th>
	</tr>

	<% @users.each do |user| %>
	<tr>
		<td><%= user.id %></td>
		<td><%= link_to( user.email, {:controller => 'users', :action => 'show', :id => user.id} ) %></td>
	</tr>
	<% end %>
</table>

app/views/users/new.html.erb
<h2>Add new User</h2>

<%= form_for(:user, :url => {:controller => 'users', :action => 'create'}, html: { multipart: true }) do |form| %>
	<%= render(:partial => "shared/user_form", :locals => {:form => form}) %>
<% end %>

app/views/users/show.html.erb
<h1>User Info</h1>

<p>User Name: <%= @user.first_name %>  <%= @user.last_name %></p>
<p>User Mail: <%= @user.email %></p>
<p>User Image: <%= @user.user_avatar %></p>

<%= link_to( "Edit User", {:controller => 'users', :action => 'edit', :id => @user.id} ) %>
<br>
<%= link_to( "Delete User", {:controller => 'users', :action => 'destroy', :id => @user.id} ) %>